/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface NumenorConfig {
    instructDate?: boolean;
    instructFloatCast?: boolean;
    instructArbitraryLimit?: boolean;
    model: string;
    temperature: number;
    bestOf: number;
    frequencyPenalty: number;
    logprobs: number;
    presencePenalty: number;
    topP: number;
    stop: string[];
}
