/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type QueryStatus = "processing" | "running" | "succeeded" | "failed";

export const QueryStatus = {
    Processing: "processing",
    Running: "running",
    Succeeded: "succeeded",
    Failed: "failed",
} as const;
