/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { QueryApi } from "@fern-api/query";

export interface QueriesPage {
    data: QueryApi.Query[];
    total: number;
    page: number;
}
