/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { QueryApi } from "@fern-api/query";

export interface Query extends QueryApi.Resource {
    user: QueryApi.User;
    name?: string;
    status: QueryApi.QueryStatus;
    lastError?: string;
    question: string;
    database: QueryApi.Database;
    config: QueryApi.NumenorConfig;
    code: string;
    result: QueryApi.Result;
    parentQuery: string;
    relevantQuestion: string[];
    run: boolean;
}
