/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { QueryApi } from "@fern-api/query";
import * as core from "../../../../core";

export const RecycleResponse: core.serialization.ObjectSchema<
    serializers.RecycleResponse.Raw,
    QueryApi.RecycleResponse
> = core.serialization.object({
    authorization: core.serialization.string(),
});

export declare namespace RecycleResponse {
    interface Raw {
        authorization: string;
    }
}
