/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors";

export class NotFoundError extends errors.QueryApiError {
    constructor() {
        super({
            message: "NotFoundError",
            statusCode: 404,
        });
        Object.setPrototypeOf(this, NotFoundError.prototype);
    }
}
