/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { QueryApi } from "@fern-api/query";
import * as core from "../../../../core";

export const ApiKeysPage: core.serialization.ObjectSchema<serializers.ApiKeysPage.Raw, QueryApi.ApiKeysPage> =
    core.serialization.object({
        data: core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).ApiKey)),
        total: core.serialization.number(),
        page: core.serialization.number(),
    });

export declare namespace ApiKeysPage {
    interface Raw {
        data: serializers.ApiKey.Raw[];
        total: number;
        page: number;
    }
}
