/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class QueryApiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, QueryApiTimeoutError.prototype);
    }
}
