/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ListPublicDatabasesRequest {
    limit?: number;
    page?: number;
    sort?: number;
    expand?: string;
}
