/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { QueryApi } from "@fern-api/query";

export interface UpdateDatabaseRequest {
    name: string;
    tables: Record<string, QueryApi.Table>;
    description?: string;
    image?: string;
    public: boolean;
}
