/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { QueryApi } from "@fern-api/query";

export interface ApiKeysPage {
    data: QueryApi.ApiKey[];
    total: number;
    page: number;
}
