/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { QueryApi } from "@fern-api/query";

export interface ApiKey {
    user: QueryApi.User;
    name: string;
    key: string;
    lastUsed?: number;
}
