/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { QueryApi } from "@fern-api/query";

export interface Database extends QueryApi.Resource {
    user: QueryApi.User;
    name: string;
    description?: string;
    image?: string;
    public: boolean;
    sourceDetails?: QueryApi.SourceDetails;
    schemaVersion: number;
    tables: Record<string, QueryApi.Table>;
    exampleQuestions: string[];
    lastSynced: number;
    source: string;
}
