/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SourceDetails {
    databaseUrl?: string;
    databaseUrlIv?: string;
    csvUrl?: string;
    csvId?: string;
    searchPath?: string[];
}
