/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { QueryApi } from "@fern-api/query";
import * as core from "../../../../../core";

export const CreateApiKeyRequest: core.serialization.Schema<
    serializers.CreateApiKeyRequest.Raw,
    QueryApi.CreateApiKeyRequest
> = core.serialization.object({
    name: core.serialization.string(),
});

export declare namespace CreateApiKeyRequest {
    interface Raw {
        name: string;
    }
}
