/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { QueryApi } from "@fern-api/query";
import * as core from "../../../../core";

export const QueriesPage: core.serialization.ObjectSchema<serializers.QueriesPage.Raw, QueryApi.QueriesPage> =
    core.serialization.object({
        data: core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).Query)),
        total: core.serialization.number(),
        page: core.serialization.number(),
    });

export declare namespace QueriesPage {
    interface Raw {
        data: serializers.Query.Raw[];
        total: number;
        page: number;
    }
}
