/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { QueryApi } from "@fern-api/query";
import * as core from "../../../../core";

export const QueryStatus: core.serialization.Schema<serializers.QueryStatus.Raw, QueryApi.QueryStatus> =
    core.serialization.enum_(["processing", "running", "succeeded", "failed"]);

export declare namespace QueryStatus {
    type Raw = "processing" | "running" | "succeeded" | "failed";
}
