/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { QueryApi } from "@fern-api/query";
import * as core from "../../../../../core";

export const UpdateQueryRequest: core.serialization.Schema<
    serializers.UpdateQueryRequest.Raw,
    QueryApi.UpdateQueryRequest
> = core.serialization.object({
    code: core.serialization.string(),
    name: core.serialization.string().optional(),
});

export declare namespace UpdateQueryRequest {
    interface Raw {
        code: string;
        name?: string | null;
    }
}
