/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { QueryApi } from "@fern-api/query";
import * as core from "../../../../../core";

export const LoginWithEmailRequest: core.serialization.Schema<
    serializers.LoginWithEmailRequest.Raw,
    Omit<QueryApi.LoginWithEmailRequest, "redirect">
> = core.serialization.object({
    email: core.serialization.string(),
});

export declare namespace LoginWithEmailRequest {
    interface Raw {
        email: string;
    }
}
