/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { QueryApi } from "@fern-api/query";
import * as core from "../../../../../core";

export const RecycleRequest: core.serialization.Schema<serializers.RecycleRequest.Raw, QueryApi.RecycleRequest> =
    core.serialization.object({
        authorization: core.serialization.string(),
    });

export declare namespace RecycleRequest {
    interface Raw {
        authorization: string;
    }
}
