/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { QueryApi } from "@fern-api/query";
import * as core from "../../../../../core";

export const UpdateDatabaseRequest: core.serialization.Schema<
    serializers.UpdateDatabaseRequest.Raw,
    QueryApi.UpdateDatabaseRequest
> = core.serialization.object({
    name: core.serialization.string(),
    tables: core.serialization.record(
        core.serialization.string(),
        core.serialization.lazy(async () => (await import("../../../..")).Table)
    ),
    description: core.serialization.string().optional(),
    image: core.serialization.string().optional(),
    public: core.serialization.boolean(),
});

export declare namespace UpdateDatabaseRequest {
    interface Raw {
        name: string;
        tables: Record<string, serializers.Table.Raw>;
        description?: string | null;
        image?: string | null;
        public: boolean;
    }
}
