/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { QueryApi } from "@fern-api/query";
import * as core from "../../../../core";

export const DatabasesPage: core.serialization.ObjectSchema<serializers.DatabasesPage.Raw, QueryApi.DatabasesPage> =
    core.serialization.object({
        data: core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).Database)),
        total: core.serialization.number(),
        page: core.serialization.number(),
    });

export declare namespace DatabasesPage {
    interface Raw {
        data: serializers.Database.Raw[];
        total: number;
        page: number;
    }
}
