/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { QueryApi } from "@fern-api/query";
import * as core from "../../../../core";

export const Table: core.serialization.Schema<serializers.Table.Raw, QueryApi.Table> = core.serialization.record(
    core.serialization.string(),
    core.serialization.lazyObject(async () => (await import("../../..")).Column)
);

export declare namespace Table {
    type Raw = Record<string, serializers.Column.Raw>;
}
