/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Column {
    dataType?: string;
    isPrimaryKey?: boolean;
    isForeignKey?: boolean;
    referencedTable?: string;
    referencedField?: string;
    hashed?: boolean;
    excluded?: boolean;
    enum?: unknown[];
}
