/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { QueryApi } from "@fern-api/query";

export interface User extends QueryApi.Resource {
    name: string;
    email: string;
    avatar: string;
    admin: boolean;
    lastLogin?: number;
}
