/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const QueryApiEnvironment = {
    Production: "https://api.query.co/api",
    Staging: "https://staging-api.query.co/api",
    Develop: "http://localhost:7000/api",
} as const;

export type QueryApiEnvironment =
    | typeof QueryApiEnvironment.Production
    | typeof QueryApiEnvironment.Staging
    | typeof QueryApiEnvironment.Develop;
