/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { QueryApi } from "@fern-api/query";
import * as core from "../../../../core";

export const Resource: core.serialization.ObjectSchema<serializers.Resource.Raw, QueryApi.Resource> =
    core.serialization.object({
        id: core.serialization.string(),
        object: core.serialization.string(),
        created: core.serialization.number(),
        test: core.serialization.boolean(),
    });

export declare namespace Resource {
    interface Raw {
        id: string;
        object: string;
        created: number;
        test: boolean;
    }
}
